### ISSUE TITLE
Non REST API fallback

### ISSUE THREAD

**Issue by pento** [swissspidy/oEmbed-API#10]
In the event that the REST API doesn't make it into WordPress 4.4, I'd like us to have a fallback method for generating the oEmbed JSON, so that we're not scrambling to throw it together at the last minute.

**Comment by tnorthcutt** [comment]
Maybe I'm missing something obvious, but if we can generate it without the REST API, why not just do that in the first place? That would give us back-compat to embed from installs older than 4.whenevertherestapigetsin, yes?

**Comment by pento** [comment]
Ideally, we don't want to duplicate work. :-)

I agree that there's extra benefit in having this plugin live on for sites that don't upgrade to 4.4 immediately.

**Comment by swissspidy** [comment]
Doing this without the REST API is easy, as can be seen here: https://wordpress.org/plugins/oembed-provider/. It's just important that it won't break when we switch to the REST API later (see #1).

Thanks to the API we don't have to worry about lots of things like rewrites, checking for required params, sanitizing the params, etc.

But if we aim for the same release as the API, we don't have to worry about that…

**Comment by pfefferle** [comment]
What about two different classes (`WP_API_oEmbed_Endpoint` and `Classic_oEmbed_Endpoint`) that handle the special parts, like registering URLs or add rewrite cases and request handlers. And both request handlers will call a generic action/filter (like https://github.com/pfefferle/wordpress-oembed-provider/blob/master/oembed-provider.php#L87), so we can add a generic output handler (like https://github.com/pfefferle/wordpress-oembed-provider/blob/master/oembed-provider.php#L102).

**Comment by swissspidy** [comment]
There's a working version now in the [`issue-10`](https://github.com/swissspidy/oEmbed-API/tree/issue-10) branch. Feedback welcome.

**Comment by swissspidy** [comment]
This has been merged into `master`. Works quite well so far both with and without the REST API. It just needs some more testing (unit tests and user tests)
