### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by pento** [swissspidy/oEmbed-API#103]
If the post contains emoji, they won't be displayed in browsers that don't have native emoji support.

`print_emoji_detection_script()` and `print_emoji_styles()` provide the necessary output to fix this.

**Comment by pento** [comment]
For performance, it's critical that `print_emoji_detection_script()` be called before any CSS is sent.

**Comment by swissspidy** [comment]
Should we just hardcode these functions or hook into the head action? Perhaps move the action hook before the CSS or add a new hook.

**Comment by pento** [comment]
It's a little bit funky, because we hardcode everything in the template - for comparison, it's hooked into `wp_head` in core, just before `wp_print_styles` happens.

**Comment by pento** [comment]
Actually, I've just done some testing, it looks like there isn't enough CSS to cause performance problems when the emoji JS runs. Let's just hook into `oembed_head`.
