### ISSUE TITLE
XML Response

### ISSUE THREAD

**Issue by pento** [swissspidy/oEmbed-API#11]
The oEmbed spec allows for an XML response, I'm wondering if we should provide that for wider interoperability.

**Comment by swissspidy** [comment]
From oEmbed.com:

> *501 Not Implemented* should be sent when (for example) the request includes format=xml and the provider doesn't support XML responses. However, providers are encouraged to support both JSON and XML.

If it's easy to do with the REST API, why not?

**Comment by swissspidy** [comment]
According to Ryan we can _"subclass the server class and use XML serialisation there instead, or we can use one of the pre-output filters to just output XML instead of JSON"_.
