### ISSUE TITLE
Send JS for non-WordPress sites

### ISSUE THREAD

**Issue by pento** [swissspidy/oEmbed-API#116]
If a non-WordPress site tries to embed the iframe from a WordPress site, it won't have the JS necessary to receive messages from the iframe.

If we send the JS along with the iframe, WordPress will strip it out automatically, but other sites will be able to keep it in if they want.

**Comment by swissspidy** [comment]
I just thought about using `wp_enqueue_script` for the JS yesterday, but this here is another good reason for not doing it.

I'll work on a PR today.

Making the JS smaller would be good, i.e. by removing any unneeded whitespace.

**Comment by pento** [comment]
For making the JS smaller, we can use the same trick as we did with the emoji frontend script - uglify it, then embed it directly in the PHP, to remove the `readfile()`. No need to worry about that until merge, though.

**Comment by swissspidy** [comment]
Perfect :)

**Comment by swissspidy** [comment]
I need to reopen this because the JS isn't properly stripped out in `wp_filter_oembed_result`.

The JS is displayed as text both in the preview and on the frontend.

**Comment by swissspidy** [comment]
Adding `script` to `$allowed_html` would at least properly execute the JS. However, we need to properly strip out the JS for embeds from WordPress sites.
