### ISSUE TITLE
Add wrapper element to embed

### ISSUE THREAD

**Issue by johnbillion** [swissspidy/oEmbed-API#119]
The resulting `<iframe>` element for an embed should either have a wrapper element (eg. a `<div>` with an appropriate `class` attribute) or have its own `class` attribute added so it's easy to target with CSS.

**Comment by swissspidy** [comment]
:+1:

When embedding a post in WordPress the iframe is inside a `<p>`, so I guess a `class` attribute makes more sense than an extra `<div>` around the `<iframe>`.
