### ISSUE TITLE
Disabling the feature

### ISSUE THREAD

**Issue by pento** [swissspidy/oEmbed-API#12]
We don't necessarily need a single filter to disable everything, but it should be possible to disable the various moving parts through the addition or removal of existing actions and filters.

If we need to add more parts, this should be taken into account.

**Comment by pfefferle** [comment]
I think it is enough to keep the focus on the `get_oembed_endpoint_url` which is (accessible via a filter) and `wp_oembed_add_discovery_links` to enable or disable autodiscovery. So I think we can close this ticket.

**Comment by swissspidy** [comment]
I'm sure someone would want to disable the `/embed/` rewrite endpoint (so nobody can embed the page) and the API endpoints (just like someone would want to disable the REST API)

**Comment by swissspidy** [comment]
Disabling the rewrite endpoint:

```php
remove_action( 'init', 'wp_oembed_rewrite_endpoint' );
```

Disabling the legacy controller:

```php
function my_remove_oembed_query_vars( $query_vars ) {
	unset $query_vars['oembed'];
	return $query_vars;
}
add_filter( 'query_vars', 'my_remove_oembed_query_vars' );
```

Disabling the REST API route:

```php
function my_disable_oembed_route( $endpoints ) {
	unset $endpoints['/wp/v2/oembed'];
	return $endpoints;
}
add_action( 'rest_endpoints', 'my_disable_oembed_route' );
```

Disabling auto discovery:

```php
add_filter( 'embed_oembed_discover', '__return_false' );
```

Can someone confirm that these (untested) filters are working and suffice to disabling the various moving parts of the plugin?

**Comment by swissspidy** [comment]
As discussed today, we should make it simpler, i.e. by using just 1 filter as a kill switch. One big red "off" button

**Comment by pento** [comment]
On further reflection, I don't like the "off" filter idea. It's adding extra code for the vast minority of users, who already have a [valid method](https://gist.github.com/swissspidy/4289519f048c30b5f77e) to disable it.

**Comment by swissspidy** [comment]
Me neither, but maybe we can make that current method a bit more simple?

**Comment by swissspidy** [comment]
See https://github.com/swissspidy/disable-embeds

The plugin will be added to the plugin repository after [#34207](https://core.trac.wordpress.org/ticket/34207) lands in core.
