### ISSUE TITLE
Show iframe in addition to the URL in the sharing dialog

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/oEmbed-API#128]
As just mentioned on Slack, the share link should also promote the embeddable `<iframe>` code for non-WordPress sites.

I know that we discarded this idea once, but we probably should reconsider it.

I'll work on the initial PR. After that it would be great to have feedback from the design team,

cc @melchoyce

**Comment by swissspidy** [comment]
@ocean90 mentioned that a textarea would look nice for the embed code.

**Comment by melchoyce** [comment]
Cool cool. Can you post a screenshot in here when you have something?

**Comment by swissspidy** [comment]
@melchoyce This is how it currently looks like:

<img width="626" alt="e03e3b9c-6233-11e5-8d61-d3d85d022c41" src="https://cloud.githubusercontent.com/assets/841956/10080274/123d32fe-62ef-11e5-96d3-42b05816d4e5.png">

Let me know what you think. Also, #137 could see some feedback as well.

**Comment by melchoyce** [comment]
There's a lot of small tweaks I'd like to make here — let me see if I can get it working locally so I can update the strings and css myself.

**Comment by melchoyce** [comment]
Taking a "tab" approach instead of having them both visible:

<img width="639" alt="screen shot 2015-09-29 at 10 00 53 am" src="https://cloud.githubusercontent.com/assets/2846578/10166242/1d9b4b18-6691-11e5-8c63-bcc11c8c9cea.png">
<img width="639" alt="screen shot 2015-09-29 at 10 01 00 am" src="https://cloud.githubusercontent.com/assets/2846578/10166243/1dc624a0-6691-11e5-8987-f2314a3d0f9a.png">

This will work better on shorter embeds.

PSD: https://cloudup.com/cJojxOlaTsC

**Comment by swissspidy** [comment]
Thanks @melchoyce!

It currently looks like this in the plugin:

<img width="622" alt="screen shot 2015-09-29 at 20 38 14" src="https://cloud.githubusercontent.com/assets/841956/10175639/6af72d3c-66f0-11e5-9981-0f199c4c7a32.png">
<img width="611" alt="screen shot 2015-09-29 at 20 38 07" src="https://cloud.githubusercontent.com/assets/841956/10175638/6af436d6-66f0-11e5-8571-16ade8f7cef6.png">

**Comment by swissspidy** [comment]
Besides some small visual quirks here I still need to improve keyboard navigation. See http://www.w3.org/WAI/PF/aria-practices/#toolbar and http://heydonworks.com/practical_aria_examples/#tab-interface.

**Comment by swissspidy** [comment]
Fixed in 30a6fd4505aeaa0870707c61752dfc86e11b06b8
