### ISSUE TITLE
oEmbed making bad Slack embeds

### ISSUE THREAD

**Issue by pento** [swissspidy/oEmbed-API#138]
Example: https://wordpress.slack.com/archives/core-restapi/p1443136051001349

We should see if we can make it better in Slack.

**Comment by swissspidy** [comment]
Yep, I'm aware of it. We should send a note to feedback@slack.com with that URL. Perhaps it gets fixed when they white-list WordPress.org. Otherwise we need to remove the script tag...

**Comment by swissspidy** [comment]
I just sent them an email. Let's see how fast they'll respond :)

For reference, here's a screenshot of the bug:

<img width="882" alt="screen shot 2015-09-25 at 08 18 01" src="https://cloud.githubusercontent.com/assets/841956/10094308/87fdece4-635e-11e5-96dc-8f33671e1faf.png">

**Comment by swissspidy** [comment]
Current status:

> I have forwarded your message to the team and hopefully we'll have you white-listed soon. I will get back to you once I hear back from the team.

**Comment by rmccue** [comment]
It looks like Slack's taking the first element of the response and just returning the content of that. Could we add something like `<noscript><?php the_content() ?></noscript>` to the start of the response?

**Comment by pfefferle** [comment]
:thumbsup:

**Comment by rmccue** [comment]
Ah, alas, it appears to use the content of *every* element:
<img width="397" alt="screenshot 2015-09-30 16 18 52" src="https://cloud.githubusercontent.com/assets/21655/10185766/fd8b8424-678e-11e5-8797-24541bcee798.png">

**Comment by swissspidy** [comment]
Argh, too bad. That would have been a nice little fix :disappointed:

**Comment by swissspidy** [comment]
In the meantime we can use the text fallback added in #161 to simply return a link instead of the iframe.

Just asked Dominik to do that.

**Comment by swissspidy** [comment]
Delivering `link` response data fixed the problem the WordPress Slack channel :smiley: 

We used something like this:

``` php
add_action( 'plugins_loaded', function() {
    // See https://github.com/swissspidy/oEmbed-API/commit/4cd1b13c515ff4ee0f6b22ffe0cacf2d87d25e0d
    // See https://api.slack.com/robots
    if ( false !== strpos( $_SERVER['HTTP_USER_AGENT'], 'Slackbot-LinkExpanding' ) ) {
        remove_filter( 'oembed_response_data', 'get_oembed_response_data_rich' );
    }
}, 20 );
```

**Comment by danielbachhuber** [comment]
If we're shipping this to 1/4 of the web, shouldn't we fix the problem more broadly? Every WordPress site linked to in Slack will have this problem.
