### ISSUE TITLE
Get height from iframes on load

### ISSUE THREAD

**Issue by pento** [swissspidy/oEmbed-API#139]
With the merge of #132, it's possible for an iframe to load and send the `height` message before the JS is loaded, particularly if the JS is moved to the footer.

To solve this, I think the best option would be to send a message from the host window to the iframes, telling them we're ready to get the height now.

**Comment by swissspidy** [comment]
Currently the iframes send the height all the time once they're loaded, so this shouldn't be a problem.

<img width="1440" alt="screen shot 2015-09-25 at 08 37 49" src="https://cloud.githubusercontent.com/assets/841956/10094512/f00e8274-6360-11e5-8d77-6f0ae154e315.png">

**Comment by swissspidy** [comment]
We could change the setTimeout interval from 50 to 100 or so though.

**Comment by pento** [comment]
Oh, that's a bug. So, there are two parts here:

* The `height` message is sent on `load`.
* When the `resize` event occurs, it sends the `height` message, then waits 50ms before sending it again.

The bug is that is keeps sending the `height` message after the `resize` event has stopped triggering.

**Comment by swissspidy** [comment]
> The bug is that is keeps sending the `height` message after the `resize` event has stopped triggering.

Alright. I greatly simplified the resize handler in #141. Now it properly waits 100ms (instead of 50 as it seemed enough) between sending the `height` message.

The `height` message is sent (and received) twice in my tests when loading the page, even when the JS is loaded in the footer.

I'm not sure _this_ bug actually exists.
