### ISSUE TITLE
HTML output filtering

### ISSUE THREAD

**Issue by pento** [swissspidy/oEmbed-API#14]
To allow sites to provide their own custom embed HTML, they should be able to filter or bypass the  default output.

See also: #12

**Comment by swissspidy** [comment]
Currently there's the `rest_oembed_html` filter to return something else than a `<iframe>` tag.

Users could hook into the `rest_oembed_output` action early, print something else and then call `exit` to prevent further output. -> Good enough or is a filter more appropriate?

**Comment by morganestes** [comment]
One thing I did recently was to customize the embed HTML on a per-post-type basis, but I used a double filter: the base 'rest_oembed_response_data' filter, plus a an additional one for the post type.

```php
$response_data = apply_filters( 'rest_oembed_response_data', array(
		'version'       => '1.0',
		'provider_name' => get_bloginfo( 'name' ),
		'provider_url'  => get_home_url(),
		'author_name'   => get_bloginfo( 'name' ),
		'author_url'    => get_home_url(),
		'title'         => get_the_title( $post ),
		'type'          => 'rich',
		'permalink'     => get_the_permalink( $post ),
		'thumbnail'     => get_the_post_thumbnail( $post->ID ),
		'html'          => get_the_oembed_excerpt( $post ),
	), $post );

	/**
	 * Filter the response data based on post type.
	 *
	 * @since 0.2.0
	 *
	 * @param array    $response_data The data returned from the 'rest_oembed_response_data' filter.
	 * @param \WP_Post $post          Response WP_Post object.
	 */
	$response_data = apply_filters( "rest_oembed_response_data_{$post->post_type}", $response_data, $post );
```

This let me separate out all my filtered responses into their own file, then each one got applied on the post type.

**Comment by swissspidy** [comment]
The HTML template is now in its own file (`includes/template.php`) and loaded by hooking into `template_include`:

`add_filter( 'template_include', 'wp_oembed_include_template' );``

This means everyone who wants to have different HTML in the iframe can just hook into that as well. Example:

```
function my_awesome_oembed_template( $template ) {
	global $wp_query;

	if ( isset( $wp_query->query_vars['embed'] ) ) {
		return 'path/to/some/template.php';
	}

	return $template;
}
```

As for the API response, the `rest_oembed_response_data` should suffice for returning something else than an `<iframe>`.

**Comment by swissspidy** [comment]
Reopening this to see if we can perhaps fine-tune things.

Potential use cases:

* Add additional content, like the author or something
* Add a tracking script
* Completely custom iframe output

The last case is easy, like mentioned above. Custom HTML markup probably needs to be done this way or added via JavaScript.

A `oembed_head` action or similar could be added to the `<head>` section. People could then add custom JavaScript and CSS. For comparison, the RSS feeds have plenty of actions in the template. We could copy some things from there.

Definitely against using `wp_head()` here.
