### ISSUE TITLE
Preserve existing window.onload function

### ISSUE THREAD

**Issue by david-binda** [swissspidy/oEmbed-API#142]
We had to revert the plugin from being used on WordPress.com since it was breaking some of the functionality (of oEmbed providers primarily).

From my initial investigation it looks like the issue could have been resolved if the plugin were preventing all existing window.onload functions. Eg.:

```
var existingOnload = window.onload;
window.onload = function () {
    if ( typeof existingOnload == 'function' ) { existingOnload(); }
    ...
```

**Comment by swissspidy** [comment]
Thanks for creating the issue!

That really is an oversight on our end. I will merge the fix into master in a couple of minutes.

**Comment by pento** [comment]
It slipped my mind that we needed to rewrite that bit of code. It should be attaching to the `load` event, like how we do with the emoji loader:

https://core.trac.wordpress.org/browser/trunk/src/wp-includes/js/wp-emoji-loader.js#L75

**Comment by swissspidy** [comment]
:+1: Can do that later the day.
