### ISSUE TITLE
Don't create functions and variables in global namespace

### ISSUE THREAD

**Issue by david-binda** [swissspidy/oEmbed-API#146]
Since the frontend.js is meant to be included on a broad variety of websites, it might be a good idea to not create variables and functions in global namespace in order to not possibly override or get overridden by someone else's code.

Encapsulating the whole code into a self-invoking anonymous function should do the trick.

**Comment by david-binda** [comment]
@swissspidy I've just reviewed the functions.php and it seems that I originally missed the fact that the JavaScript being outputted in https://github.com/swissspidy/oEmbed-API/blob/master/includes/functions.php#L119 is actually dependant on existence of `receiveEmbedMessage` in global namespace.

We might need to expose some of the functions and/or variables at global level then. Perhaps having a single prefixed object? Thoughts?

Could this issue be reopened?

**Comment by swissspidy** [comment]
My bad, in my limited testing I didn't think of that. Perhaps we can kust strip this check. The script tag is stripped out on WordPress sites anyway. It becomes a problem when a non-WP site jas many embedd though.

**Comment by swissspidy** [comment]
@pento What's your take on this?

**Comment by pento** [comment]
We can put it in the `wp` namespace. See wp-emoji.js for an example.
