### ISSUE TITLE
Embed restrictions

### ISSUE THREAD

**Issue by pento** [swissspidy/oEmbed-API#15]
There are at least a couple of extra restrictions that `filter_oembed_result()` needs to put in place.

* Enforce our desired attributes
* Only allow a single iframe

... maybe other things?

**Comment by swissspidy** [comment]
* We need to allow other tags too, like `<p>`, `<a>`, `<img>` and so on. See also #13
* Pass an array of allowed protocols to `wp_kses` to only allow for `http` and `https`

**Comment by pento** [comment]
For #13, we still only need to allow an iframe - because we can allow JS in the iframe, we can resize it to fit the content, per #16. The only thing we need to worry about here is sanity checking the iframe tag returned by the content provider.

**Comment by swissspidy** [comment]
> > We need to allow other tags too, like `<p>`, `<a>`, `<img>` and so on. See also #13
>
> For #13, we still only need to allow an iframe

Correct, but some non-WordPress providers may not be returning iframes, but paragraphs or links.

**Comment by pento** [comment]
We can't allow random tags, as it'll open a huge window for targeted attacks.

For example, say a popular site embeds an attacker's URL. To begin with, they'll show the correct output, to not raise suspicion. Once the embed is live and seeing lots of clicks, it's easy for them to change it to a full screen link, because most large sites have CSS in place to show a popover that takes up the entire screen.

When the end user clicks the popup to remove it, they'll be directed to a site the attacker controls (which looks like a login page for the site they just came from).
