### ISSUE TITLE
Code Formatting

### ISSUE THREAD

**Issue by pento** [swissspidy/oEmbed-API#152]
Scrutinizer is noting a handful of code formatting changes that need to be made - spacing, indentation, etc.

Let's merge them before we get to merging into Core.

**Comment by swissspidy** [comment]
I should probably adjust the Scrutinizer settings. The proposed patches are all not adhering the WP coding standards:

https://scrutinizer-ci.com/g/swissspidy/oEmbed-API/inspections/f9a924aa-cbe0-4bed-b1fb-09bba0e77143/patches?status=all

**Comment by pento** [comment]
Hah, I was reading the patches the wrong way around - yep, ignore those suggestions. :-)
