### ISSUE TITLE
Site Icon misaligned in Safari 8

### ISSUE THREAD

**Issue by pfefferle** [swissspidy/oEmbed-API#153]
see: http://notizblog.org/2015/07/25/indiewebcamp-2014-this-is-a-movement/embed/

**Comment by swissspidy** [comment]
With broken you mean pixelated? Or am I missing something?

We're currently downscaling the 32px image to 25px.

Perhaps we could add a new 24px site icon size during the merge.

**Comment by pfefferle** [comment]
No, it is shifted from the text (Mac/Safari).

![bildschirmfoto 2015-09-28 um 14 16 18](https://cloud.githubusercontent.com/assets/2373/10135133/b3b3aa9c-65eb-11e5-8cf3-d8acfa486bc8.png)

**Comment by pfefferle** [comment]
Without the `top: 50%;` it looks fine: https://github.com/swissspidy/oEmbed-API/blob/master/includes/template.php#L137

**Comment by swissspidy** [comment]
Looks good to me in Safari 9.0.1 (11601.2.4). Which version are you using?

**Comment by pfefferle** [comment]
The latest final version: 8.0.8 (10600.8.9)

**Comment by pfefferle** [comment]
It seems ok in every other actual browser though...

**Comment by swissspidy** [comment]
@pfefferle Could you try adding `-webkit-transform: translateY(-50%);` in addition to `transform: translateY(-50%);` (instead of removing `top: 50%;`)? AFAIK Webkit in Safari 8 still needs that prefix.

**Comment by pfefferle** [comment]
:+1: this will fix it!

**Comment by pfefferle** [comment]
Thanks ;)
