### ISSUE TITLE
Add search engine headers

### ISSUE THREAD

**Issue by pento** [swissspidy/oEmbed-API#157]
To ensure that search engines don't scrape the embed, we should add

`<link rel="canonical" href="..." />`

and 

`<meta name="robots" content="noindex" />`

**Comment by swissspidy** [comment]
I think we can simply hook `wp_no_robots()` (uses `noindex, follow`) and `rel_canonical` to the `oembed_head` action.

**Comment by pento** [comment]
:+1:

**Comment by swissspidy** [comment]
Works:

```html
<meta name='robots' content='noindex,follow' />
<link rel="canonical" href="http://src.wordpress-develop.dev/2015/09/27/test-audio/" />
```
