### ISSUE TITLE
Issue with height calculation

### ISSUE THREAD

**Issue by FlorianBrinkmann** [swissspidy/oEmbed-API#162]
I have a problem with the height calculation again (I use Firefox on Windows 10, looks the same in Edge)… You can see it on these two sites:

http://florianbrinkmann.de/1414/wordpress-wochenrueckblick-kw-37-wordpress-und-php7-shortcodes-und-mehr/ 
http://florianbrinkmann.de/1441/wordpress-inhalte-auf-eurer-seite-einbetten-oembed-api-machts-moeglich/

![unbenannt](https://cloud.githubusercontent.com/assets/2310924/10218049/4ac6e2a6-6834-11e5-9306-779eaeea26f1.PNG)

![unbenannt](https://cloud.githubusercontent.com/assets/2310924/10218057/5cf3b5ee-6834-11e5-9693-f93cae282cd8.PNG)

The height seems to be limited to 338px.

**Comment by swissspidy** [comment]
@FlorianBrinkmann Try clearing the oEmbed cache on both posts. The iframes are missing the `wp-embedded-content` class. Clearing the oEmbed cache (e.g. by removing the `_oembed_` postmeta entries from the database for that post) should fix that.

**Comment by FlorianBrinkmann** [comment]
Works, thanks! :)
