### ISSUE TITLE
Syntax errors in frontend.js

### ISSUE THREAD

**Issue by Latz** [swissspidy/oEmbed-API#164]
1.)
SyntaxError: missing } after function body
...ndow.wp = window.wp || {};	// Don't execute this twice.	if ( !! window.wp.receiv..

Don't know why but the error could be resolved by changing the comment characters:
	/* Don't execute this twice. */

2.) Missing semicolon in line 15 (we're using strict after all)

3.)
After removing error 1 and 2 I get 

SyntaxError: missing } in compound statement
'DOMContentLoaded', onLoad, false );} )( window, document );

Could not resolve it though.

**Comment by swissspidy** [comment]
Good catch! Cn you try the latest version and see if you still get errors?

Which browser are you using?

**Comment by Latz** [comment]
Does work now. (Waterfox 40)

**Comment by Latz** [comment]
Error 3 was caused by another plugin in my installation. Sorry for any inconvenience.
