### ISSUE TITLE
endpoint name

### ISSUE THREAD

**Issue by Latz** [swissspidy/oEmbed-API#165]
The plugin provides an endpoint named "/embed/. Looking at the providers in "class-oembed.php" all endpoints are named "oembed". For consistency it may be a good idea to name it "oembed", too.

**Comment by swissspidy** [comment]
Yes, the URLs of those endpoints often end in `/oembed`. These are the oEmbed API endpoints that return JSON or XML data.

The `/embed` rewrite endpoint you're talking about is used for the embeddable post template, available at eample.com/my-awesome-post/embed/. That template is optimized for being embedded in the iframe.

The oEmbed API endpoint you mean is either accessible via example.com/?oembed=true or example.com/wp-json/v2/oembed (with the REST API).
