### ISSUE TITLE
Embedded vs Linked CSS

### ISSUE THREAD

**Issue by pento** [swissspidy/oEmbed-API#17]
Is it better for us to embed the CSS in the iframe, or link it as a file from the source?

PageSpeed recommends inlining "small" CSS resources.

https://developers.google.com/speed/docs/insights/InlineCSS

**Comment by swissspidy** [comment]
If we can avoid additional HTTP requests and maybe even could minify the inline CSS, I'm definitely not against it.

**Comment by tnorthcutt** [comment]
+1 for inlined and minified CSS over an extra http request.

**Comment by pento** [comment]
Inline works for me.

We can investigate minifying after merge to core.
