### ISSUE TITLE
Merge /develop branch

### ISSUE THREAD

**Issue by pento** [swissspidy/oEmbed-API#19]
The develop branch is pretty ugly, but it seems we're waiting on it to get better before we merge it to master.

I think we should just merge it, live with the ugly for now, and improve it as we go on. This will particularly be helped by hooking this into the W.org auto-commit system, and adding it to the Beta Tester tab.

Any objections?

**Comment by swissspidy** [comment]
Yeah it would be great to have it in the repository as early as possible.

We just need to make sure the oEmbed output is good enough so people can already use it.

**Comment by pento** [comment]
At the moment it's good enough to see it working - paste a link, see the preview in the editor, see the embed on the post.

It's ugly, but I'd like for us to not be held up by waiting for an undefined "not ugly".

**Comment by pento** [comment]
Merged in 3fbf443.
