### ISSUE TITLE
Disable XML Entity Expansion in the XML generation

### ISSUE THREAD

**Issue by pento** [swissspidy/oEmbed-API#22]
This probably isn't an attack vector for this code, but I'd prefer to be safe than sorry.

See: https://core.trac.wordpress.org/changeset/29378

**Comment by swissspidy** [comment]
I understand this to be an error when _parsing_ XML strings, not _generating_ them.

**Comment by rmccue** [comment]
Indeed, it's only applicable when parsing, not when generating.
