### ISSUE TITLE
Implement sharing dialog

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/oEmbed-API#24]
Now that our embeds look great, it's time to add the sharing dialog in the bottom right corner.

Clicking on the share icon should:

* Reveal the URL
* Reveal the embed code

Both values should be in input fields so people can copy them easily.

**Comment by melchoyce** [comment]
Why both the url and the embed?

Here's what I have so far for the sharing dialog: 

![embed-test-1-noquote-share](https://cloud.githubusercontent.com/assets/2846578/9009580/37c11d88-3770-11e5-93c8-5309bc41c5a2.jpg)

Also want to try out something a little more subtle.

**Comment by swissspidy** [comment]
Dunno… Probably forgot for a second that only the URL is needed to embed the post :)

Definitely prefer a simple sharing dialog like this. I'd even remove the copy button. [Copying still requires Flash](http://caniuse.com/#feat=clipboard) to work. Alternatively, we could just select the whole text input when the user clicks on it.

**Comment by melchoyce** [comment]
WFM :+1:

**Comment by pento** [comment]
+1 on selecting the text when the user clicks/taps (or when the dialog opens).

Does the Clipboard API support feature detection? If so, we can just show the Copy button in browsers that support it. I'd definitely like to avoid using the Flash method.

**Comment by swissspidy** [comment]
Nope, no feature detection per se. We could only check for the user agent like GitHub does: https://gist.github.com/jonrohan/81085b119d16cdd7868a. Not really a fan of this though...

That's why the people over at [zeroclipboard](https://github.com/zeroclipboard/zeroclipboard) haven't implemented this yet.

Looks like in the future you may even have to ask the user for permission to copy things to the clipboard.

Creating a follow-up issue for this.

**Comment by pento** [comment]
Wow, that's terrible. I guess we'll have to leave it for now.
