### ISSUE TITLE
REST API schema

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/oEmbed-API#32]
From the REST API docs:

> A "schema" is a representation of the format for WP-API's response data. For instance, the Post schema communicates that a request to get a Post will return id, title, content, author, and other fields. Our schemas also indicate the type each field is, provide a human-readable description, and show which contexts the field will be returned in.

Wouldn't it be helpful for developers adding a schema for our oEmbed endpoint?

**Comment by rmccue** [comment]
The schema follows the [JSON Schema](http://json-schema.org/) spec if you want to read up on how to write one. :)

**Comment by swissspidy** [comment]
Hmm this first pass was actually pretty bad. An oEmbed response can have different properties depending on the type. As soon as I get the unit test with the OPTIONS request to work, I'll update this.
