### ISSUE TITLE
Embedding non-WordPress sites that haven't been whitelisted

### ISSUE THREAD

**Issue by pento** [swissspidy/oEmbed-API#34]
Presumable, non-WordPress sites won't be providing an iframe for their oEmbed HTML, so their HTML will be stripped out, and it'll appear all funky in the editor, and on the published post.

If we have to strip out lots of HTML, perhaps we should assume we can't handle that endpoint, and `filter_oembed_result()` should return `false`, instead, so no embed is created.

**Comment by swissspidy** [comment]
Do you have a specific example of a broken embed or is this just a general issue?

Perhaps something like this is already enough:

```
if ( '' === $html ) {
    return false;
}
```

**Comment by pento** [comment]
No example, just assuming things will explode for most non-WordPress sites. :-)

I think checking that there's HTML would be enough.
