### ISSUE TITLE
Core Bug: Capabilities

### ISSUE THREAD

**Issue by pento** [swissspidy/oEmbed-API#38]
Currently, the plugin only works when the user has `unfiltered_html` capabilities.

This bug will need to be fixed in core as part of the merge.

**Comment by swissspidy** [comment]
Ah, I see:

>  Discovery is disabled for users lacking the unfiltered_html capability.

(from the `WP_oEmbed` class)

Good to know!

**Comment by swissspidy** [comment]
@pento Where in core does the capability check happen? Can we write a patch beforehand?

**Comment by pento** [comment]
In `WP_Embed::shortcode()`:

`$attr['discover'] = ( apply_filters( 'embed_oembed_discover', false ) && author_can( $post_ID, 'unfiltered_html' ) );`

We just need to remove the `author_can()` check, we'll be setting the default value of `embed_oembed_discover` to `true` at the same time.
