### ISSUE TITLE
Precommit tasks

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/oEmbed-API#4]
It'd be nice to run PHPMD, phpunit and PHPCS checks easily through one simply command, like `grunt precommit` in core.

`grunt phpunit` already works, but I think we should add the others, too. Basically remove those dependencies from `composer.json` and add the according npm packages.

**Comment by danielbachhuber** [comment]
> It'd be nice to run PHPMD

Do you find PHPMD useful, out of curiosity?

**Comment by ntwb** [comment]
Fixed via 5774302

**Comment by swissspidy** [comment]
@danielbachhuber The tool hasn't _that_ many rules, but it's always great to have someone complaining if you're doing it wrong. Especially at the beginning, I like the information about too complex classes and methods.
