### ISSUE TITLE
Bring the mockups to life

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/oEmbed-API#5]
Current status:
<img width="784" alt="screen shot 2015-07-20 at 2 13 07 pm" src="https://cloud.githubusercontent.com/assets/841956/8808005/3ed8a0ec-2fe0-11e5-9b9b-741a8c61a492.png">

The mockups we need to implement in HTML:
![embed-test-1-noquote 1](https://cloud.githubusercontent.com/assets/841956/8808101/d2071c5e-2fe0-11e5-8821-da64c3324869.jpg)

Any volunteers?

**Comment by mhmli** [comment]
Happy do do the HTML, but is there actually a need for the CSS? As it will
be delivered in the theme in the embedding site, won't it? Or what's the
plan?

**Comment by swissspidy** [comment]
@mhmli As this is something that should work out of the box, we can't rely on themes styling these embeds. Therefore we need to do both the HTML and CSS.

**Comment by mhmli** [comment]
Shouldn't be a problem. Is this version going to work via iFrame?

**Comment by melchoyce** [comment]
Put together an HTML/CSS prototype here: http://codepen.io/melchoyce/full/EjOxwY/

Still missing what happens when you tap the sharing icon.

**Comment by swissspidy** [comment]
Closing this in favour of #5 and potentially other issues.

Currently it looks like this:

<img width="635" alt="screen shot 2015-07-31 at 11 09 27" src="https://cloud.githubusercontent.com/assets/841956/9004329/5f421128-3775-11e5-9128-d938ab3df58b.png">
