### ISSUE TITLE
iframe's security and sandbox attributes don't play nicely

### ISSUE THREAD

**Issue by pento** [swissspidy/oEmbed-API#53]
It seems that, when the `security` attribute is set, it will over-ride the `sandbox="allow-scripts"` attribute, even in IE10.

See: http://stackoverflow.com/a/20071528

**Comment by pento** [comment]
Removing it probably isn't the right fix. 

`sandbox` isn't supported in IE8/9. There's very little documentation (nothing solid) that discussed the exact behaviour, so I think we're just going to need to test it - see if we're able to attack older IE versions when they don't have the `security` attribute.

**Comment by swissspidy** [comment]
From the [MSDN blog](http://blogs.msdn.com/b/ie/archive/2008/01/18/using-frames-more-securely.aspx):

> For frames rendered in Internet Explorer 6 and later, security can be further increased by setting the frame’s `SECURITY` attribute to the value “restricted”.  Doing so causes Internet Explorer to treat the contents of the frame, regardless of their source, as content that should be rendered in the Restricted Sites Security Zone.  Frames running in the Restricted Sites zone cannot run script, invoke ActiveX controls, redirect to other sites, and so on. This technique is particularly useful in cases where the frame’s content cannot be assumed to be trustworthy (as in the case of web mail scenario above).
>
> In the best case, frames are tagged with the `SECURITY="restricted"` attribute to ensure that the HTML email or the advertisement cannot contain any script which might be used to navigate the user away from the web mail page to a malicious site (e.g. `<SCRIPT>window.location="http://evil.example.net/malice.htm"</SCRIPT>`).

**Comment by swissspidy** [comment]
And from [the docs](https://msdn.microsoft.com/en-us/library/ms534622):

> The security attribute affects the behavior of hyperlinks and forms inside a restricted frame or iframe in the following two ways.
> * Hyperlinks and forms open in a new window. This happens even when the target attribute specifies "_self" for a frame nested in the restricted frame.
> * The security attribute restricts use of the javascript, vbscript, and about protocols in the URL. For example, in a restricted frame or iframe, the source file cannot execute the following code.
> ```
<a href="javascript:alert('Disallowed in restricted FRAME or IFRAME!');">JavaScript Link</a>
```

Sounds like two things we'd actually want and my removal was a bit overeager.

**Comment by pento** [comment]
The best suggestion I've seen so far is, in IE10+, delete the original `iframe`, then dynamically re-add it without the `security` attribute.

The `security` attribute can't be removed from an element once it's been added.

I'm hoping we can come up with a method that doesn't involve page content jumping around, though.

**Comment by swissspidy** [comment]
> I'm hoping we can come up with a method that doesn't involve page content jumping around, though.

User Agent detection? 😁

Or perhaps something like this works:

1. Add invisible placeholder with the same width and height and place it over the iframe with CSS.
2. Remove original iframe
3. Add new iframe
4. Remove placeholder. Nothing should have been jumping around

Don't know how feasible this is, if it'd be compatible with all themes etc.

**Comment by pento** [comment]
If we can remove the old iframe, then add and resize the new iframe in the same function, I don't think it'll cause jumping - the page shouldn't re-render until after the function is finished. There'll just be an iframe content flicker if the iframe has already started loading when we do the replacement.

Ideally, we'd only be doing this the other way around - if a browser doesn't support `sandbox`, add the `security` attribute. I'm not sure if we can do this securely, though - the `security` attribute would need to be added before the `iframe` content is loaded.
