### ISSUE TITLE
Embeds from different domains don't render

### ISSUE THREAD

**Issue by kanenas** [swissspidy/oEmbed-API#62]
<strong>WordPress Core</strong>: v.4.3
<strong>Theme</strong>: Twenty Fifteen
<strong>oEmbed API</strong>: v.0.5.0-20150910

I tried to embed posts from different domains but they failed to render.

*Example*: http://www.my-soul.net/blog/this-is-another-post/ 

Do the websites from which I embed posts must have <strong>oEmbed API</strong> WordPress plugin installed in order to work?

**Comment by swissspidy** [comment]
Yes the plugin is required on both ends for various reasons.
