### ISSUE TITLE
Hide (remove) block of comments if comments are not allowed in a post

### ISSUE THREAD

**Issue by kanenas** [swissspidy/oEmbed-API#63]
I have seen in many WordPress installations that administrators don't allow comments on posts.
It would be nice to have an option to "Show", "Hide" comments from the embedded posts.

I think by using ```comments_open( $post_id )``` https://codex.wordpress.org/Function_Reference/comments_open could handle that.

**Comment by swissspidy** [comment]
Good catch! Will fix this ASAP.
