### ISSUE TITLE
iFrame height limit of 600px is too small

### ISSUE THREAD

**Issue by FlorianBrinkmann** [swissspidy/oEmbed-API#65]
Hi!
I have installed the oEmbed plugin today on my site and have one problem:

![oembed-error](https://cloud.githubusercontent.com/assets/2310924/9810637/688ff8da-5872-11e5-9133-98dc7aeaf95b.PNG)

I want to embed a post with a featured image but it doesn't show the whole iFrame. It's cropped on the bottom. This is the post I want to embed: http://florianbrinkmann.de/1339/twenty-sixteen-das-neue-standard-theme-fuer-wordpress-in-der-kurzvorstellung/
The post with the problem is not live yet so I can't link to it.

**Comment by swissspidy** [comment]
Hi Florian

Thanks for your report! Great to hear you're testing the plugin :)

I want to test this on my site too, but the oEmbed discovery links are missing on your site. Is the `wp_head()` call perhaps missing in the `<head>` section of your theme? We're using that hook to display the discovery links, see https://github.com/swissspidy/oEmbed-API/blob/master/includes/functions.php#L11.

**Comment by kanenas** [comment]
@swissspidy, in the ```header.php``` file of the <strong>Twenty Sixteen</strong> WordPress theme has...
```
<head>
	<meta charset="<?php bloginfo( 'charset' ); ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="profile" href="http://gmpg.org/xfn/11">
	<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">
	<?php wp_head(); ?>
</head>
```

**Comment by FlorianBrinkmann** [comment]
Should work now, it was Cachify :)

**Comment by swissspidy** [comment]
On my sites it works well, so I suspect it's Cachify. I heard of problems with Cachify and oEmbed before. Make sure JS and HTML minification are disabled there and try it again. Also try to embed other posts.

If it still doesn't work, [clear your oEmbed cache](https://github.com/swissspidy/oEmbed-API/issues/61#issuecomment-139247492) (for your draft post or the whole site), and try it again.

Ps. Thanks for blogging about the plugin :)

**Comment by FlorianBrinkmann** [comment]
I've tried the following:

* Deactivated Cachify
* Deleted the _oembed entries from wp_postmeta

But it looks the same as before in my draft. It works great with posts without featured images and better on posts with lower featured images (for example: http://florianbrinkmann.de/1392/wordpress-wochenrueckblick-kw-36-shortcode-roadmap-term-meta-und-mehr/).
I updated an older post with an embed of this post so you can see the problem “in real”: http://florianbrinkmann.de/1392/wordpress-wochenrueckblick-kw-36-shortcode-roadmap-term-meta-und-mehr/

It seems that the iFrame doesn't want to be taller than 600px ...

**Comment by swissspidy** [comment]
Ah, indeed!

I thought resizing wasn't working at all, but the problem is really the height limit. See: https://github.com/swissspidy/oEmbed-API/blob/master/scripts/frontend.js#L10-L11

You can blame @pento for that :)

I'll change it to something higher, like 800px or so. I don't really want to add a new image size.

**Comment by FlorianBrinkmann** [comment]
Thanks! :)

**Comment by swissspidy** [comment]
Thanks for the hint. For that image a height of about 840px is needed depending on the iframe width.

So either we remove the limit (not a good idea), raise it to something like 1000px, or set the image height to something like 300px using CSS. Demo of the latter method:

<img width="638" alt="screen shot 2015-09-11 at 12 51 14" src="https://cloud.githubusercontent.com/assets/841956/9813204/e4aa9022-5883-11e5-9e3a-5419aa789be3.png">

Note how the image is aligned vertically (using `position: relative; top: 50%; transform: translateY(-50%);`).

**Comment by FlorianBrinkmann** [comment]
The method with cropping and centering the image works good for this image. But if you have a featured image in portrait format with more information like text or something, it could be a problem. So instead I would raise it to something like 1000px.

And why is removing the limit a bad idea?

**Comment by swissspidy** [comment]
> And why is removing the limit a bad idea?

Just imagine someone changing their site so it always sends a height of `10000px` ;)
