### ISSUE TITLE
Check whether the current post has an excerpt and display it

### ISSUE THREAD

**Issue by kanenas** [swissspidy/oEmbed-API#66]
This is just a <strong>suggestion</strong>.

In ```/includes/template.php``` file, I replaced <strong>line:397</strong> 

```<p class="wp-embed-excerpt"><?php echo $post_content; ?></p>```

with this:
```
	<p class="wp-embed-excerpt">
		<?php
		// Check whether the current post has an excerpt.
		if ( has_excerpt( $post->ID ) ) {
			echo get_the_excerpt();
		} else {
			echo $post_content;
		}
		?>
	</p>
```

*Example*: http://www.my-soul.net/blog/%CE%B1%CE%BA%CE%BF%CF%8D%CF%83%CE%B5%CE%B9-%CE%B4%CE%B9%CE%B1%CF%83%CF%86%CE%B1%CE%BB%CE%AF%CE%B6%CE%B5%CF%84%CE%B1%CE%B9-%CE%BC%CE%B5%CF%84%CE%B1%CE%B3%CE%BB%CF%89%CF%84%CE%B9%CF%83%CF%84%CE%AE%CF%82/

**Comment by swissspidy** [comment]
Makes sense.

I think we can even just use `the_excerpt()` and filter `the_excerpt` to add our custom output with the word count.

**Comment by kanenas** [comment]
:+1:
