### ISSUE TITLE
Add ability to preview the response from the editor

### ISSUE THREAD

**Issue by morganestes** [swissspidy/oEmbed-API#90]
It would be nice to be able to preview the response from a page/post that's being edited so editors can tweak content if necessary. I've done this with a meta box and editor styles, but would love to know of other options available.

**Comment by swissspidy** [comment]
Interesting idea! I would probably use that feature on some sites, but I don't think the majority would.

Perhaps you can share your current solution with us to have a better picture of it?

**Comment by morganestes** [comment]
I'll check to see what parts of it I can release, since it's tied into a client theme, and update here when I can. 

The general idea is to make an oEmbed request to the post via `get_oembed_response()`, get the response JSON, then create a new instance of our `oEmbed_Meta_Preview` class to add the meta box with the styled response `$response_data['html']`.

The issues I had the most problems with were caching (embedding a post into another post caches the response in that post's meta) and with unpublished posts that `get_oembed_response()` couldn't reach.

**Comment by swissspidy** [comment]
Cool, no rush. I really like that idea and it would be great to make at least a separate plugin out of it.

Reminds me of Buzzfeed, where editors can see a mobile preview of their articles right away (and can't publish without looking at it)

**Comment by swissspidy** [comment]
I'm closing this for now as it isn't really something for core but a separate plugin instead. One that I'd really like to work on :)

`get_oembed_response` probably isn't needed. We could simply embed the iframe in a separate meta box and refresh it occasionally.
