### ISSUE TITLE
Embed Truncated on iPhone

### ISSUE THREAD

**Issue by mrjarbenne** [swissspidy/oEmbed-API#91]
The embed frame seems to be cut off when viewing the post on an iPhone screen. I'm seeing this behaviour on both Twenty Fifteen, and the mobile theme from the latest version of WP-Touch

WP 4.3
OEmbed API 0.7.0-20150914

![image](https://cloud.githubusercontent.com/assets/480667/9865726/dfb666f8-5b27-11e5-98b7-39411e7d2324.png)

**Comment by swissspidy** [comment]
Looks like the reason for this is the [Responsive Videos](http://jetpack.me/support/responsive-videos/) module of Jetpack. It simply resizes every iframe it finds, even though we do the resizing ourselves.

It's [a known bug](https://github.com/Automattic/jetpack/pull/2440) in Jetpack and hopefully resolved soon.

Untested, but the following should disable that for now:

```php
remove_filter( 'embed_oembed_html',  'jetpack_responsive_videos_embed_html' );
```

**Comment by mrjarbenne** [comment]
Nice catch. Cheers.
