### ISSUE TITLE
Multisite, subdirectory configs.

### ISSUE THREAD

**Issue by imath** [swissspidy/oEmbed-API#97]
I need to check this again, but it seems in this configuration:

- It's possible to embed any post from a single WordPress site.
- It's possible to embed a post from the same site eg blog.url/site1 will be able to embed  blog.url/site1/hello-world

- But it's not possible to embed a post form any other site of the network. Eg on blog.url/site1 i cannot embed blog.url/blog/hello-world and vice / versa
- When i'm trying to embed a post from blog.url/site1 or from the root blog (blog.url) on another WordPress single site, it's not working

**Comment by imath** [comment]
Mmm, i guess the fact i was testing on a config using the same domain eg locahost/single-site and localhost/multisite is a bit confusing.

On 2 different domain names, i'm not able to embed another WordPress site

**Comment by swissspidy** [comment]
> On 2 different domain names, i'm not able to embed another WordPress site

Do you mean two sites in a Multisite install with different domains?

What I'm taking from your notes so far is that embedding on Multisite doesn't work as expected yet, or not work _at all_.

**Comment by imath** [comment]
Sorry, i wasn't clear. 

On a multisite using subdirectories it's only working when you embed a post belonging to the blog.

blog.url/subsite/hello-world embedded in blog.url/subsite works. But embedding it on the root blog doesn't seem to work for me.

But this may be the right behavior as it seems the feature is not available if you try to embed a post from another WordPress install. Or i'm missing something ;)

For me trying to embed develop.url/hello-world/ in test.url is not working.

imath.
http://profiles.wordpress.org/imath/

**Comment by swissspidy** [comment]
Thanks for the clarification

> On a multisite using subdirectories it's only working when you embed a post belonging to the blog.

Hmm the plugin runs fine on the make blogs though. I'll see if I can find any problems on a local multisite install.

> But this may be the right behavior as it seems the feature is not available if you try to embed a post from another WordPress install.

Both installs need to have the plugin active in order for the embedding to work.

**Comment by imath** [comment]
Thanks.

I'll check on my side too. The tests i've made were with a multisite and a regular with the plugin activated for both configs (network activated for the multisite).

The only thing i don't have is the WP Rest API.

imath.
http://profiles.wordpress.org/imath/

**Comment by swissspidy** [comment]
> The only thing i don't have is the WP Rest API.

It's not needed :)

**Comment by imath** [comment]
Ok, it looks like cross domain Ajax on local vhosts are blocked by browsers, which is annoying when testing.

I've just tested on 2 regular Websites and i agree it's working.

Unfortunately, i'm not able to test for multisite on real internet sites. But i think as the domain is the same in multisite subdirectory configs, there's still a problem when trying to embed a post from any blog of the network into the root blog.

**Comment by swissspidy** [comment]
@imath Could you test #113 on your multisite install? It tries to fix this bug a bit earlier.

**Comment by imath** [comment]
@swissspidy Looks like it's fixing it :) 

But i've been working on some multisite unit tests and they are failing with #113 while they are not failing with the patch i've been working on. Very strange...

**Comment by imath** [comment]
Here are the unit tests, just in case

https://gist.github.com/imath/8137da1a0913a3c98b38

**Comment by swissspidy** [comment]
Awesome, thanks for the tests!

> But i've been working on some multisite unit tests and they are failing with #113 while they are not failing with the patch i've been working on. Very strange...

That's because my patch changes/fixes the behaviour your patch relies on.

Previously, when you tried to embed a post from a child site on the main site, the following happened:

1. WordPress checks all registered providers and finds `home_url( '/*' )`
2. Because that matches with the child site, WordPress loads the main site's API endpoint

With my patch applied, the following happens:

1. WordPress loads the URL via `wp_remote_get` and looks for the oEmbed discovery tags
2. It then loads the URL referenced in the discovery tag, which is the oEmbed endpoint of the child site

This should actually be the desired behaviour. And it even works with separate WordPress installs in subfolders and not just multisite.

You can put the `restore_current_blog` in the `test_request_ms_child_in_root_blog` test at the end of the method to make it work (i.e. load the child site's endpoint, not the main site's).

Note: With my patch, the other two tests seem redundant because you don't need to switch back to the old site to test the endpoint. That's why they're not in my latest update to #113

**Comment by imath** [comment]
Thanks a lot for your explanations and your great work to solve the issue :) imath http://profiles.wordpress.org/imath
      De : Pascal Birchler <notifications@github.com>
 À : swissspidy/oEmbed-API <oEmbed-API@noreply.github.com> 
Cc : imath <mathchristo@yahoo.fr> 
 Envoyé le : Lundi 21 septembre 2015 18h48
 Objet : Re: [oEmbed-API] Multisite, subdirectory configs. (#97)
   
Awesome, thanks for the tests!
But i've been working on some multisite unit tests and they are failing with #113 while they are not failing with the patch i've been working on. Very strange...
That's because my patch changes/fixes the behaviour your patch relies on.Previously, when you tried to embed a post from a child site on the main site, the following happened:   
   - WordPress checks all registered providers and finds home_url( '/*' )
   - Because that matches with the child site, WordPress loads the main site's API endpoint
With my patch applied, the following happens:   
   - WordPress loads the URL via wp_remote_get and looks for the oEmbed discovery tags
   - It then loads the URL referenced in the discovery tag, which is the oEmbed endpoint of the child site
This should actually be the desired behaviour. And it even works with separate WordPress installs in subfolders and not just multisite.You can put the restore_current_blog in the test_request_ms_child_in_root_blog test at the end of the method to make it work (i.e. load the child site's endpoint, not the main site's).Note: With my patch, the other two tests seem redundant because you don't need to switch back to the old site to test the endpoint. That's why they're not in my latest update to #113—

**Comment by swissspidy** [comment]
Fixed in #113
