### ISSUE TITLE
Share icons should use circle focus

### ISSUE THREAD

**Issue by melchoyce** [swissspidy/oEmbed-API#98]
Right now the focus styling is the rectangular default:

<img width="689" alt="screen shot 2015-09-17 at 12 11 41 pm" src="https://cloud.githubusercontent.com/assets/2846578/9941908/81876298-5d35-11e5-869f-7812933ce156.png">

It would look better as a circle, like in https://core.trac.wordpress.org/ticket/33808.

**Comment by swissspidy** [comment]
Indeed that would look better!

I see that in core a combination of box-shadow, padding and border-radius is used. I'll try to implement this in a non-hacky way :)

Any other things we should look out for?

**Comment by melchoyce** [comment]
The comment focus is pretty wonky looking:

<img width="67" alt="screen shot 2015-09-17 at 12 48 59 pm" src="https://cloud.githubusercontent.com/assets/2846578/9942971/9139af92-5d3b-11e5-9223-e3dbc8b86d84.png">

A circle could look good over the icon there, but not with the number. Maybe even just figuring out a way for it to be a smooth rectangle would be good.

**Comment by swissspidy** [comment]
Agree, a circle for only half of the clickable area seems strange. I'll try to make it a proper rectangle.
